# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linippet < Formula
  desc "One-liner snippet generator for shell."
  homepage "https://github.com/muleyuck/linippet"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muleyuck/linippet/releases/download/v0.3.0/linippet_Darwin_x86_64.tar.gz"
      sha256 "d29bf99ebe9ab1df97ee09438af3eb4c8aa43a62ebd7b31b8b22cb95c84b81fb"

      def install
        bin.install "linippet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muleyuck/linippet/releases/download/v0.3.0/linippet_Darwin_arm64.tar.gz"
      sha256 "ac3968520b31bac19a744e8d145920482f2c190ab07bfd58b929caa93814af0c"

      def install
        bin.install "linippet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muleyuck/linippet/releases/download/v0.3.0/linippet_Linux_x86_64.tar.gz"
      sha256 "68aca763d620324ff82c41a2578262220c0f3ad6c11809c45707b43c19969675"
      def install
        bin.install "linippet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muleyuck/linippet/releases/download/v0.3.0/linippet_Linux_arm64.tar.gz"
      sha256 "99e32809f388f538bd74b3e5f36dc34a13d100c954c99893c5ecfeac155bcdf3"
      def install
        bin.install "linippet"
      end
    end
  end
end
