# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Linippet < Formula
  desc "One-liner snippet generator for shell."
  homepage "https://github.com/muleyuck/linippet"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/muleyuck/linippet/releases/download/v0.2.4/linippet_Darwin_x86_64.tar.gz"
      sha256 "38eaf4a391d161c665ba956c491bb7d9934de749066a5e7a6bd281ef14000581"

      def install
        bin.install "linippet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/muleyuck/linippet/releases/download/v0.2.4/linippet_Darwin_arm64.tar.gz"
      sha256 "a42ac1896d11438e0534d0d21657c4d8839e509449beef6f014c1b40ee8bb765"

      def install
        bin.install "linippet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/muleyuck/linippet/releases/download/v0.2.4/linippet_Linux_x86_64.tar.gz"
      sha256 "4f9cde3de927cba13cffc33609f390c1e1dc6e52a61003c887621cdf649494a5"
      def install
        bin.install "linippet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muleyuck/linippet/releases/download/v0.2.4/linippet_Linux_arm64.tar.gz"
      sha256 "96c8ccab44dcfe29d4e21458a315a80240a3abe2dfadfeb829b03dfaac0591f8"
      def install
        bin.install "linippet"
      end
    end
  end
end
